# Generated by Django 5.2.4 on 2025-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('html', models.FileField(upload_to='games/<django.db.models.fields.CharField>')),
                ('apk', models.FileField(upload_to='games/<django.db.models.fields.CharField>')),
                ('icon', models.ImageField(upload_to='games/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
