# Generated by Django 5.2.4 on 2025-08-09 12:55

import apps.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='apk',
            field=models.FileField(upload_to=apps.games.models.Game.get_file_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='html',
            field=models.FileField(upload_to=apps.games.models.Game.get_file_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(upload_to=apps.games.models.Game.get_file_path),
        ),
    ]
