# Generated by Django 5.2.4 on 2025-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0014_jobguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='play_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
