# Generated by Django 5.2.4 on 2025-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hub", "0015_alter_game_play_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ml",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("s_id", models.CharField(blank=True, max_length=15, null=True)),
                ("desc", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="ml_images"),
                ),
                ("git_link", models.URLField(blank=True, max_length=300, null=True)),
                ("play_url", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
